<table class=buttonmenu width=100%>
  <tr>
    <td class="navbarbutton"><a href="index.php" class=button>Admin-Index</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="templates.php" class=button>Templates</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="general.php" class=button>General</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="display.php" class=button>Data Display</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="listdisplay.php" class=button>Data Lists Display</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="clantag.php" class=button>Clan Tag Management</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="ranking.php" class=button>Ranking</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="clear-text.php" class=button>Clear-Text</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="mod-assign.php" class=button>Mod Assignment</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="categories.php" class=button>Categories</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="password.php" class=button>Change Password</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="rem_players.php" class=button>Remove Players</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="rem_rounds.php" class=button>Remove Rounds</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="reset.php" class=button>Reset Stats</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="../index.php" class=button>back to Statistic</a></td>
  </tr>
  <tr>
    <td class="navbarbutton"><a href="logout.php" class=button>Logout</a></td>
  </tr>
</table>