<table class=buttonmenu width=100%>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="index.php" class=button>Admin-Index</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="templates.php" class=button>Templates</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="general.php" class=button>General</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="display.php" class=button>Data Display</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="listdisplay.php" class=button>Data Lists Display</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="clantag.php" class=button>Clan Tag Management</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="ranking.php" class=button>Ranking</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="clear-text.php" class=button>Clear-Text</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="mod-assign.php" class=button>Mod Assignment</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="categories.php" class=button>Categories</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="password.php" class=button>Change Password</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="rem_players.php" class=button>Remove Players</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="rem_rounds.php" class=button>Remove Rounds</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="reset.php" class=button>Reset Stats</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="../index.php" class=button>back to Statistic</a></td>
  </tr>
  <tr>
    <td class=buttonInActive onMouseOver="this.className='buttonActive'; this.style.cursor='hand';" onMouseOut="this.className='buttonInActive';"><a href="logout.php" class=button>Logout</a></td>
  </tr>
</table>